### ISSUE TITLE
access_token: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by ofirshtrull** [030/golang-bitbucket-cloud-build-status-notifier#3]
Hi when I try to run with the latest version I get the next error 

```$ docker run utrecht/golang-bitbucket-cloud-build-status-notifier:1.0.1 -keyString dg6DvhHhjT5gYQZCPE:MYPASSWORD -buildState SUCCESSFUL -gitCommit d5d24e56325d0ad938141ee1556cbce4a3d6f926 -owner owner -repositoryName MYCOMPANY-upgrade-service -buildNumber 13 -buildURL http://jenkins.MYCOMPANY.io:8080/job/archive_builds/job/upgrade-service/job/jenkinsfile-test/20/```

2019/03/26 08:44:09 Post https://bitbucket.org/site/oauth2/access_token: x509: certificate signed by unknown authority

**Comment by 030** [comment]
Thank you for reporting this. I was able to reproduce the issue and this seems to be related to the docker image as this does not occur when the binary is used.

**Comment by 030** [comment]
@ofirshtrull Could you test whether the latest image solves the issue? I just tried it and the issue has been solved on my machine.

**Comment by ofirshtrull** [comment]
Works great!

Thanks
